version: '2'
volumes:
  database_data:
    driver: local
  bundle_cache:
    driver: local
services:
  db:
    build: ./db/
    ports:
      - 3333:5432
    volumes:
      - database_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
